youtube:
  backends:
    - invidious
    - yt-dlp
    - yt-dlp-native
  instance:
    - https://invidious.example.com

instagram:
  proxy: http://localhost:8080
  download_proxy: http://localhost:8081
